name: 04 - Using Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: install
        run: |
          pwd
          cd 04-using-actions/react-app
          npm install
          ls -alh
      - name: Remove Unused files
        run: |
          pwd
          cd ..
          rm -rf .git .github .gitignore README.md
          mv 04-using-actions/react-app .
          rm -rf 04-using-actions
      - name: List final setup
        run: |
          pwd
          ls -alh
