name: 6 - Contexts
on:
  push:
  workflow_dispatch:

jobs:
  echo-data:
    runs-on: ubuntu-latest
    environment: bebe
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor : ${{ github.actor }}"
          echo "Workflow name : ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          echo "Secret: ${{ vars.MY_VAR || 'not defined' }}"
