name: 6 - Contexts
on:
  push:
  workflow_dispatch:
env:
  MY_WORKFLOW_VAR: workflow
  MY_OVERWRITTEN_VAR: workflow
jobs:
  echo-data:
    runs-on: ubuntu-latest
    environment: bebe
    env:
      MY_JOB_VAR: job
      MY_OVERWRITTEN_VAR: job
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
      - name: Retrieve Variable
        run: |
          echo "Secret: ${{ vars.MY_VAR || 'not defined' }}"
      - name: Print Env Variables
        run: |
          echo "MY_WORKFLOW_VAR:  ${{ env.MY_JOB_VAR }}"
          echo "MY_JOB_VAR: $MY_JOB_VAR"
          echo "MY_OVERWRITTEN_VAR: $${{ env.MY_OVERWRITTEN_VAR }}"
